- title: "IT Consultancy"
  svg: "/assets/images/undraw_sharing_knowledge_03vp.svg"
  description: "Providing optimal solutions for your problems that can be solved with IT."

- title: "Content Creation"
  svg: "/assets/images/undraw_social_dashboard_re_ocbd.svg"
  description: "Photo shoots, video editing, and SNS management to help you reach your target audience."

- title: "Travel Consultancy"
  svg: "/assets/images/undraw_stranded_traveler_pdbw.svg"
  description: "Creating personalized itineraries based on your preferences and needs."
