- title: "IT Consultancy"
  svg: "/assets/images/undraw_sharing_knowledge_03vp.svg"

- title: "Content Creation"
  svg: "/assets/images/undraw_social_dashboard_re_ocbd.svg"

- title: "Travel Consultancy"
  svg: "/assets/images/undraw_stranded_traveler_pdbw.svg"
